sudo: required
services:
 - docker
before_install:
 - gem install rake
 - docker build -t janko01/docker-react -f Dockerfile.dev .
script:
 - docker run janko01/docker-react npm run test -- --coverage