sudo: required
services:
    - docker
    
before_install:
    - docker build -t jankotest/docker-react -f Dockerfile.dev .
    
scripts:
    - docker run jankotest/docker-react npm run test -- --coverage